
title: "scRNA-seq analysis of PBMC from COVID-19 patients of the Padova cohort"
short_title: "covidiamo-padova"
subtitle: |
   The code and the data in this repository enables the reproduction of the analyses and plots for 
   the single-cell RNA-seq data in the paper "RAGE engagement by SARS-CoV-2 enables monocyte infection and
   underlies COVID-19 severity" (https://doi.org/10.1101/2022.05.22.492693).

pages:

  Differential abundance analysis:
    notebook: "02_abundance_analysis_cell_families.html"
    description: |
      This is the RMarkdown code that has been used to compute the differential abundance of the
      cell families that have been recognized in the dataset. 
